config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :price_per_night, numericality: { only_integer: true }
  validates :number_of_guests, numericality: { only_integer: true, :in => 0..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: %i[show edit destroy]

  def index
    @flats = Flat.all
    @flat = Flat.new
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
  end

  def destroy
    @flat.destroy
    redirect_to flats_path
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(%i[name address price_per_night number_of_guests])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<h1>Edit Flat</h1>
<%= simple_form_for(@flat) do |f| %>
<%= f.input :name %>
<%= f.input :address %>
<%= f.input :number_of_guests %>
<%= f.input :price_per_night %>
<%= f.submit %>
<% end %>

app/views/flats/index.html.erb
<div class="form-container" data-controller="show-form">
  <div class="form d-none" data-show-form-target="form">
    <h5>New Flat</h5>
    <%= simple_form_for(@flat) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :number_of_guests %>
    <%= f.input :price_per_night %>
    <%= f.submit %>
    <% end %>
  </div>
</div>
<div class="header-container">
  <div class="header">
    <h3>See all flats (<%= @flats.count %>)</h3>
  </div>
</div>
<div class="container">
<div class="card-container">
<% @flats.each do |f| %>
<div class="card">
  <div class="card-body">
    <h5 class="card-title"><%= f.name %></h5>
    <p class="card-text"><%= f.address %></p>
    <div class="guest-price-box">
      <div class="guest">
        <div class="guest-icon">
          <i class="fa-solid fa-user-group"></i>
        </div>
        <div class="guest-number">
          <p class="card-text"><%= f.number_of_guests %></p>
        </div>
      </div>
      <div class="price">
        <div class="price-icon">
          <i class="fa-solid fa-dollar-sign"></i>
        </div>
        <div class="price-number">
          <p class="card-text"><%= f.price_per_night %></p>
        </div>
      </div>
    </div>
  </div>
  <div class="card-footer">
  <%= link_to "More Info", flat_path(f), :class => "more-info-btn" %>
  <%= link_to "Edit", edit_flat_path(f), :class => "edit-btn" %>
  <%= link_to "Delete", flat_path(f), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, :class => "delete-btn" %>
  </div>
</div>
<% end %>
</div>
</div>

app/views/flats/new.html.erb
<h1>New Flat</h1>
<%= simple_form_for(@flat) do |f| %>
<%= f.input :name %>
<%= f.input :address %>
<%= f.input :number_of_guests %>
<%= f.input :price_per_night %>
<%= f.submit %>
<% end %>

app/views/flats/show.html.erb
<div class="image-banner">
<img src="https://source.unsplash.com/random/900×700/?room" alt="">
</div>

<h1><%= @flat.name %></h1>
<p>Address: <%= @flat.address %></p>
<p>Price per night: <%= @flat.price_per_night %></p>
<p>No. of guest: <%= @flat.number_of_guests %></p>

<%= link_to "Return to all flats", flats_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
  <div class="" data-controller="show-form">
  <div class="navbar">
  <h4 class="main-title"><%= link_to "Simple Airbnb", flats_path, :class => "home-btn" %></h4>
  <button class="btn btn-outline-primary" data-action="click->show-form#show">New Flat</button>
  </div>
  <div class="form-container">
  <div class="form d-none" data-show-form-target="form">
    <h5>New Flat</h5>
    <%= simple_form_for(@flat) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :number_of_guests %>
    <%= f.input :price_per_night %>
    <%= f.submit %>
    <% end %>
  </div>
  </div>
</div>
    <%= yield %>
  </body>
</html>